"""Unit tests for the noise layer."""

# Standard Library Imports
import hashlib
import os

# External Imports
import pytest

# Project Imports
from a23crypt import noise
from a23crypt.noise import add_noise, remove_noise


# ---------------------------------------------------------------------------
# Round-trip and keying
# ---------------------------------------------------------------------------


def test_noise_roundtrip_empty():
    seed = b"test_seed"
    assert remove_noise(add_noise(b"", seed), seed) == b""


@pytest.mark.parametrize(
    "size",
    [1, 2, 5, 10, 15, 16, 20, 50, 100, 1024, 8192],
    ids=lambda x: f"size={x}",
)
def test_noise_roundtrip_various_sizes(size):
    seed = os.urandom(32)
    data = os.urandom(size)
    noisy = add_noise(data, seed)
    assert len(noisy) > len(data)  # Noise should always increase the size unless data is empty
    assert remove_noise(noisy, seed) == data


def test_noise_different_seeds_produce_different_output():
    data = b"hello world " * 10
    seed1 = b"seed1"
    seed2 = b"seed2"
    noisy1 = add_noise(data, seed1)
    noisy2 = add_noise(data, seed2)
    assert noisy1 != noisy2


def test_noise_wrong_seed_fails_recovery():
    data = b"hello world " * 10
    seed1 = b"seed1"
    seed2 = b"seed2"
    noisy = add_noise(data, seed1)
    recovered = remove_noise(noisy, seed2)
    assert recovered != data


def test_noise_expansion_ratio():
    # Because take count is 0-15 (average ~7.5), for every ~7.5 real bytes we append 1 noise byte.
    # So length should be roughly data_len * (8.5 / 7.5) = data_len * 1.13
    data = os.urandom(10_000)
    seed = b"seed"
    noisy = add_noise(data, seed)
    ratio = len(noisy) / len(data)
    assert 1.05 < ratio < 1.20


# ---------------------------------------------------------------------------
# Wire-format stability
# ---------------------------------------------------------------------------


# SHA-256 of add_noise output, generated by the original pure-Python
# implementation (v0.1.0). Sizes straddle the scalar/vectorized cutoff;
# 65552 is a full chunk's inner-AEAD output.
_KNOWN_ANSWERS = {
    1: "168c7a3e11a6cb9a254a405a9c17549c883234e015610f4893ba24b799b3b621",
    319: "6fed54ece38ebaab890e6e41ad96579c28708f8375a10cd06b7a88d122290c64",
    320: "1fb046aa7ece6b36d89ea7133fa8a64fc9e12114badded6a5488265db00ab91e",
    4096: "515bf9b26f8233564d63ba4039afac517c7f3edbeaea9de0264c83269bf084b9",
    65552: "47533282ddd8c6d6b348545a10839048328d5f0c2bb766eeb34f845ab1bf5e72",
}


@pytest.mark.parametrize("size", _KNOWN_ANSWERS, ids=lambda x: f"size={x}")
def test_noise_known_answer(size):
    seed = bytes(range(16))
    data = hashlib.shake_256(b"kat-data").digest(size)
    noisy = add_noise(data, seed)
    assert hashlib.sha256(noisy).hexdigest() == _KNOWN_ANSWERS[size]
    assert remove_noise(noisy, seed) == data


# ---------------------------------------------------------------------------
# Vectorized path matches the scalar reference
# ---------------------------------------------------------------------------


def test_noise_vectorized_matches_scalar():
    # Every size up to 1 KiB (run clamping and loop termination vary with
    # the keystream, so each size gets its own seed), plus chunk sizes.
    for size in [*range(1, 1025), 4096, 65536, 65552]:
        seed = size.to_bytes(16, "big")
        other_seed = b"other" + seed
        data = hashlib.shake_256(b"data" + seed).digest(size)
        noisy = noise._add_noise_scalar(data, seed)

        assert noise._add_noise_vectorized(data, seed) == noisy, size
        assert noise._remove_noise_vectorized(noisy, seed) == data, size
        # Wrong seed and non-noisy input must match too: a correct
        # client_key with a wrong server_key passes the outer AEAD and
        # reaches remove_noise.
        assert noise._remove_noise_vectorized(noisy, other_seed) == (
            noise._remove_noise_scalar(noisy, other_seed)
        ), size
        assert noise._remove_noise_vectorized(data, seed) == (
            noise._remove_noise_scalar(data, seed)
        ), size


def test_noise_vectorized_keystream_fallback(monkeypatch):
    # A huge divisor leaves a 64-iteration first pass, which advances at
    # most 64 × 16 bytes — far short of 8192, so the full budget is used.
    monkeypatch.setattr(noise, "_FIRST_PASS_DIVISOR", 10**9)
    seed = bytes(16)
    data = hashlib.shake_256(b"fallback-data").digest(8192)
    noisy = noise._add_noise_scalar(data, seed)
    assert noise._add_noise_vectorized(data, seed) == noisy
    assert noise._remove_noise_vectorized(noisy, seed) == data
